# Generated by Django 3.0.2 on 2020-01-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=100)),
                ('product', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='products',
            name='product',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='snach.Seller'),
        ),
    ]
