# Generated by Django 3.0.2 on 2020-01-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snach', '0004_auto_20200122_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='amount',
        ),
    ]
